n=input("Enter the list1 elements:")
list1=n.split()
m=input("Enter the list2 elements:")
list2=m.split()
print("The list1 elements are:",list1)
print("The list2 elements are:",list2)
print("The difference is:",list(set(list1)-set(list2)))
print("The union is :",set(list1).union(set(list2)))
print("The intersection is :",set(list1).intersection(set(list2)))
